### ISSUE TITLE
default_ruby should not use :create_if_missing

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-chruby#5]
It's unexpected for my actual default_ruby to not change if I change the node_attribute.

See https://github.com/pivotal-sprout/sprout-chruby/blob/d2bd977362a4d7bcefa7cc28ef5dab97e75585b7/recipes/default_ruby.rb#L7

**Comment by aramprice** [comment]
Agreed, I think we saw this recently.

Should this be removed in both places?
